[package]
name = "common"
version = "0.2.0-SNAPSHOT"
authors = ["Calm0406"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
tokio = { version = "1.52", features = ["rt", "macros"] }
serde_json = "1.0"
dotenv = "0.15"

[dependencies]
actix-web = { version = "4.14.0", default-features = false, optional = true }
serde = { version = "1.0", features = ["derive"] }
log = "0.4.33"
dotenv = "0.15"

sqlx = { version = "0.9.0", features = ["runtime-tokio"], optional = true }
async-trait = { version = "0.1.89", optional = true }
lazy_static = "1.5.0"
quartz_sched = { version = "0.1.11", optional = true }
sqlx-oracle = { git = "https://github.com/calm04061/sqlx-oracle.git", optional = true }
sqlx-mysql = { version = "0.9.0",optional = true }

[features]
default = ["web"]
sqlx_pg = ["sqlx", "sqlx/postgres", "async-trait"]
sqlx_mysql = ["sqlx", "sqlx/mysql", "async-trait", "sqlx-mysql"]
sqlx_oracle = ["sqlx", "sqlx-oracle", "async-trait"]
quartz = ["quartz_sched"]
web = ["dep:actix-web"]
